name: Massive-Impressive
favicon: null
layout_spectrum: 0.4761961547192186
typography_spectrum: 0.06001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d8d2'
    - '#292b2a'
    - '#b8b9b3'
    - '#767771'
    - '#96978f'
  brandStrength: 0
  lightness: 0.1828612496610731
  saturation: 0
  rhythmicContrast: 0.28488653362728655
purpose: []
